---

- name: enable codeready-builder-for-rhel-8 repository
  become: true
  community.general.rhsm_repository:
    name: codeready-builder-for-rhel-8-x86_64-rpms
    state: enabled
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"

- name: enable rhel-7-server-optional-rpms rhel-7-server-extras-rpms repositories
  become: true
  community.general.rhsm_repository:
    name: 
      - rhel-7-server-optional-rpms 
      - rhel-7-server-extras-rpms
    state: enabled
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "7"

- name: install Fedora EPEL key
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    fingerprint: "{{ ansible_role_epel_fingerprint }}"
  when: ansible_distribution == "RedHat"

- name: install EPEL repositories
  become: true
  ansible.builtin.yum:
    name: "{{ ansible_role_epel_package }}"
    state: present
    update_cache: yes
