---

- name: only run on supported platforms
  block:
  - name: Include variables specific for the distribution.
    include_vars: "{{ item }}"
    with_items:
      - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

  - import_tasks: install.yml
  when: ansible_os_family == "RedHat" and ansible_distribution != "Fedora"
